#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Has to be loaded before prezto or hub completion is not loaded.
alias git="hub"

# Completion
fpath=('/usr/local/share/zsh/site-functions/' $fpath)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source vars first
source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshmodules/vars.zsh"

# Source all modules
for f in `find ${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshmodules -type f -name *.zsh`; do
    source $f
done

