#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=/usr/local/bin:/usr/local/opt/ccache/libexec:/Users/Jonathan/Library/Haskell/bin:$PATH:/Users/Jonathan/.cabal/bin:/Users/Jonathan/.rvm/gems/ruby-2.0.0-p247/bin:/Users/Jonathan/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/Jonathan/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/Jonathan/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
export GIT_EDITOR=/usr/local/bin/vim
export EDITOR=/usr/local/bin/vim
export VISUAL=/usr/local/bin/mvim
export NODE_PATH=/usr/local/lib/node_modules
export NODE_ENV="development"
export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"
eval "$(rbenv init -)"

# Git aliases:
alias git="hub"
alias got='git'
alias gut='git'
alias get='git'

alias gs='git status'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gd='git diff'
alias gdl='git diff HEAD HEAD~1'
alias goto='git checkout'
alias gk='gitk--all&'
alias gx='gitx --all'
alias gh='git hist'
alias gha='git hist --all'

# Hub aliases
alias gpr="git pull-request"

# Brew aliases
alias bup='brew update'
alias bug='brew upgrade'
alias bupg='brew update && brew upgrade'

# Vim aliases
alias vim='vim -p'

# gcc/g++ aliases
alias g++='g++-4.8'

# Servering aliases
alias serve="python -m SimpleHTTPServer"

# Node aliases
alias node="node --harmony --use-strict"
alias ni="npm install"
alias nig="npm install -g"
alias nis="npm install --save"
alias nisd="npm install --save-dev"
